spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://127.0.0.1:9097/vehcile_platform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 'TMcar-DB2018**'


server:
  port: 8180
  
staticPath: /UserFiles/cwb/web/image/