spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vehcile_platform?useUnicode=true&characterEncoding=utf-8
    username: root
    password: womenxing2014


server:
  port: 8088

#文件上传保存目录
staticPath:  D:\keystore\images\